### ISSUE TITLE
New-SSHSession not working against certain ciphers

### ISSUE THREAD

**Issue by IonutDanNica** [darkoperator/Posh-SSH#377]
Hi,

I've inherited and environment of ESXi hosts where thy are running a special list of ciphers in sshd_config of each ESXi host. 
The list is below
```
KexAlgorithms ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256

HostKeyAlgorithms ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-256,rsa-sha2-512

```

I cannot establish an SSH connection using posh-ssh 2.3.0, PS 5.1 and Windows 2019 server.
As soon as I comment out these lines I am able to connect. Is there anything that can be done for POSH-SSH to support the algo's above?

Thanks,
ionut

**Comment by darkoperator** [comment]
It would have to be something that SSH.NET would need to add. I do not control or have the skill to add those to the library

**Comment by darkoperator** [comment]
Here is the list of supported cyphers https://github.com/sshnet/SSH.NET Sent from Mail for Windows 10 From: Ionut-Dan NicaSent: Tuesday, February 9, 2021 9:02 AMTo: darkoperator/Posh-SSHCc: SubscribedSubject: [darkoperator/Posh-SSH] New-SSHSession not working against certain ciphers (#377) Hi,I've inherited and environment of ESXi hosts where thy are running a special list of ciphers in sshd_config of each ESXi host.The list is belowKexAlgorithms ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256 HostKeyAlgorithms ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-256,rsa-sha2-512 I cannot establish an SSH connection using posh-ssh 2.3.0, PS 5.1 and Windows 2019 server.As soon as I comment out these lines I am able to connect. Is there anything that can be done for POSH-SSH to support the algo's above?Thanks,ionut—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by MVKozlov** [comment]
version 3.0 support much more ciphers than 2.30 isn't it ?

**Comment by darkoperator** [comment]
The Alpha does. If I don’t get any bug reports by the end of this week will release the beta 1 next Monday, and a week after that if no bug reports the final release.  Sent from Mail for Windows 10 From: Max KozlovSent: Tuesday, February 9, 2021 10:27 AMTo: darkoperator/Posh-SSHCc: Carlos Perez; CommentSubject: Re: [darkoperator/Posh-SSH] New-SSHSession not working against certain ciphers (#377) version 3.0 support much more ciphers than 2.30 isn't it ?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by IonutDanNica** [comment]
Hi,

Any progress on the beta/final release for 3.0?

Thank you,
Ionut

**Comment by darkoperator** [comment]
New beta was pushed out at the start of the week

**Comment by pbosgraaf** [comment]
Hi,

Not trying to hijack the thread, but I'm facing the same issue and just wanted to check upon this issue.
Since posh-ssh 3.0 is out already, did the new ssh.net lib with the new cyphers got included in the final release?
In other words, do you feel it should work now?

My esx host supports:

KexAlgorithms
ecdh-sha2-nistp256
ecdh-sha2-nistp384
ecdh-sha2-nistp521
diffie-hellman-group-exchange-sha256
diffie-hellman-group16-sha512
diffie-hellman-group18-sha512
diffie-hellman-group14-sha256

Ciphers
aes256-gcm@openssh.com
aes128-gcm@openssh.com
aes256-ctr
aes192-ctr
aes128-ctr

MACs 
hmac-sha2-256
hmac-sha2-512

Most of these cyphers are listed on ssh.net as supported:
https://github.com/sshnet/SSH.NET


Thanks!

**Comment by darkoperator** [comment]
Yes

**Comment by buskeyl** [comment]
As far as I can tell you, with the most current POSH-SSH release, and the most current Esxi 7.x release as of yesterday, this still does not work.  This is with out-of-the -box ESXi settings.  Disappointing.  Does anyone know of a fix?  The same server lets me use Putty to connect to it without needing any special updates.

**Comment by wgjhstt247** [comment]
Using the latest release (v3.0.8), I can't connect to a device that uses ecdh-sha2-nistp256 key exchange. I can connect to this device using PuTTY and confirmed it's using ecdh-sha2-nistp256. The key exchange algorithm is the only difference in the initial connection setup for a non-working device vs a working device that I have. Are you sure that the latest SSH.NET library changes are included in v3.0.8 of Posh-SSH?

**Comment by darkoperator** [comment]
It is using the development branch as of late last year. In the logs on the device does it specify that cipher as the culprit?Sent from my iPhoneOn Feb 22, 2023, at 7:19 PM, Ryan ***@***.***> wrote:﻿
Using the latest release (v3.0.8), I can't connect to a device that uses ecdh-sha2-nistp256 key exchange. I can connect to this device using PuTTY and confirmed it's using ecdh-sha2-nistp256. The key exchange algorithm is the only difference in the initial connection setup for a non-working device vs a working device that I have. Are you sure that the latest SSH.NET library changes are included in v3.0.8 of Posh-SSH?

**Comment by briamorr** [comment]
I've got similar issues as well, I don't think it likes the host key algorithm (in my case trying to use RSA instead of ecdh):

Connection not working to OpenSSH Server 8.0p1 (and other devices) when server_host_key_algorithms is set to:
ssh-rsa
rsa-sha2-256
rsa-sha2-512

root        3015  0.0  0.0  92320  7812 ?        Ss   07:02   0:00 /usr/sbin/sshd -D -oCiphers=aes128-ctr,aes192-ctr,aes256-ctr -oMACs=hmac-sha1,hmac-sha2-256,hmac-sha2-512 -oGSSAPIKexAlgorithms=gss-curve25519-sha256-,gss-nistp256-sha256-,gss-group14-sha256-,gss-group16-sha512-,gss-gex-sha1-,gss-group14-sha1- -oKexAlgorithms=ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group16-sha512,diffie-hellman-group14-sha1 -oHostKeyAlgorithms=ssh-rsa,rsa-sha2-256,rsa-sha2-512 -oPubkeyAcceptedKeyTypes=ecdsa-sha2-nistp256,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-256-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-512-cert-v01@openssh.com,ssh-rsa,ssh-rsa-cert-v01@openssh.com -oCASignatureAlgorithms=ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-256,rsa-sha2-512,ssh-rsa

PS C:\temp> New-SSHSession -ComputerName "x.x.x.x" -Credential $credential  -AcceptKey:$true -Verbose -ErrorOnUntrusted
VERBOSE: Using SSH Username and Password authentication for connection.
New-SSHSession: An established connection was aborted by the server.

Works fine with ssh-ed25519 (however the end device we want to use only allows the above 3 host key types):

New-SSHSession -ComputerName "x.x.x.x" -Credential $credential  -AcceptKey:$true -Verbose -ErrorOnUntrusted
VERBOSE: Using SSH Username and Password authentication for connection.
VERBOSE: ssh-ed25519 Fingerprint for x.x.x.x: e9:25:6c:66:ba:f9:33:4c:39:f6:79:68:58:21:e3:6a
VERBOSE: Fingerprint matched trusted ssh-ed25519 fingerprint for host x.x.x.x

**Comment by darkoperator** [comment]
Yep that is a recurring issue with the library used by the module. Makntainer does not have the time or bandwidth to add additional ciphers and product are switching to stronger ciphers as a precaution, I say precaution because the ciphers they are switching from have not been broken and most customer rather go with the highest instead of properly looking at what is the real threatSent from my iPhoneOn Feb 24, 2023, at 9:26 AM, briamorr ***@***.***> wrote:﻿
I've got similar issues as well, I don't think it likes the host key algorithm (in my case trying to use RSA instead of ecdh):
Connection not working to OpenSSH Server 8.0p1 (and other devices) when server_host_key_algorithms is set to:
ssh-rsa
rsa-sha2-256
rsa-sha2-512
root        3015  0.0  0.0  92320  7812 ?        Ss   07:02   0:00 /usr/sbin/sshd -D -oCiphers=aes128-ctr,aes192-ctr,aes256-ctr -oMACs=hmac-sha1,hmac-sha2-256,hmac-sha2-512 -oGSSAPIKexAlgorithms=gss-curve25519-sha256-,gss-nistp256-sha256-,gss-group14-sha256-,gss-group16-sha512-,gss-gex-sha1-,gss-group14-sha1- -oKexAlgorithms=ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group16-sha512,diffie-hellman-group14-sha1 -oHostKeyAlgorithms=ssh-rsa,rsa-sha2-256,rsa-sha2-512 ***@***.******@***.******@***.******@***.******@***.******@***.******@***.*** -oCASignatureAlgorithms=ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-256,rsa-sha2-512,ssh-rsa
PS C:\temp> New-SSHSession -ComputerName "x.x.x.x" -Credential $credential  -AcceptKey:$true -Verbose -ErrorOnUntrusted
VERBOSE: Using SSH Username and Password authentication for connection.
New-SSHSession: An established connection was aborted by the server.
Works fine with ssh-ed25519 (however the end device we want to use only allows the above 3 host key types):
New-SSHSession -ComputerName "x.x.x.x" -Credential $credential  -AcceptKey:$true -Verbose -ErrorOnUntrusted
VERBOSE: Using SSH Username and Password authentication for connection.
VERBOSE: ssh-ed25519 Fingerprint for x.x.x.x: e9:25:6c:66:ba:f9:33:4c:39:f6:79:68:58:21:e3:6a
VERBOSE: Fingerprint matched trusted ssh-ed25519 fingerprint for host x.x.x.x

**Comment by mikemayops** [comment]
Hi, 

Can someone show me how to pick a different cipher? I'm running into the same issue and I don't see a parameter on New-SFTPSession that allows that. 

Thanks!

**Comment by darkoperator** [comment]
Yo need to modify the server you are connecting to to. The library Im using does not give me control of the ciphers to use and sadly they are not adding new onesSent from my iPhoneOn Mar 15, 2023, at 12:24 PM, Michael G. Mayoral ***@***.***> wrote:﻿
Hi,
Can someone show me how to pick a different cipher? I'm running into the same issue and I don't see a parameter on New-SFTPSession that allows that.
Thanks!

**Comment by mikemayops** [comment]
@darkoperator  Oh I see. I'll have to reach out to the vendor then since its cloud hosed. Thanks!
